services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - backend_media:/app/media
    environment:
      - FLASK_APP=src.app
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - DATABASE_URL=sqlite:///./test.db
      - JWT_SECRET_KEY=dev-secret-key-change-in-production
      # Don't commit the actual GROQ key to version control
      - GROQ_API_KEY=${GROQ_API_KEY}
      - GROQ_API_KEY_2D=${GROQ_API_KEY}
    command: flask run --host=0.0.0.0

  frontend:
    build: ./project
    ports:
      - "5173:5173"
    volumes:
      - ./project:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:5000
    command: npm run dev -- --host

volumes:
  backend_media:
